// common.js - shared code for every page of MCL-LRMS (DEMO).
// Loaded after supabase-js and config.js.

var LRMS = (function () {
  var APP = {
    name: "MCL Land & Revenue Management & Grievance Redressal System",
    short: "MCL-LRMS",
    area: "Kaniha Area (DEMO)",
    table: "lrms_records"
  };

  // ---------- Database client ----------
  var db = null, dbError = "";
  try {
    var url = window.SUPABASE_URL || "", key = window.SUPABASE_PUBLISHABLE_KEY || "";
    if (url.indexOf("PASTE") !== -1 || !key || key.indexOf("PASTE") !== -1) {
      dbError = "Database settings are not filled in yet (config.js).";
    } else if (!window.supabase) {
      dbError = "The Supabase library did not load. Check the internet connection.";
    } else {
      db = window.supabase.createClient(url, key);
    }
  } catch (e) { dbError = String(e && e.message || e); }

  // ---------- Small helpers ----------
  function $(sel, root) { return (root || document).querySelector(sel); }
  function $all(sel, root) { return Array.prototype.slice.call((root || document).querySelectorAll(sel)); }
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function fmtDate(d) {
    if (!d) return "-";
    var x = new Date(d); if (isNaN(x)) return "-";
    return x.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  }
  function fmtDateTime(d) {
    if (!d) return "-";
    var x = new Date(d); if (isNaN(x)) return "-";
    return x.toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
  }
  function errText(e) {
    if (!e) return "Unknown error";
    if (typeof e === "string") return e;
    return [e.message, e.details, e.hint, e.code].filter(Boolean).join(" | ") || String(e);
  }
  // Friendly message that also shows the actual error text (team rule 8)
  function showMsg(el, type, text, error) {
    if (typeof el === "string") el = $(el);
    if (!el) return;
    var html = "<div>" + esc(text) + "</div>";
    if (error) html += "<div class='small' style='margin-top:6px'>Error details (please pass this on): <code>" + esc(errText(error)) + "</code></div>";
    el.innerHTML = "<div class='msg " + type + "' role='" + (type === "err" ? "alert" : "status") + "'>" + html + "</div>";
  }
  function dbReady(el) {
    if (db) return true;
    showMsg(el, "err", "Sorry, the database is not connected, so this action cannot be saved.", dbError);
    return false;
  }
  function norm(s) { return String(s || "").toLowerCase().replace(/[^a-z0-9/]/g, ""); }
  function normPlot(s) { return String(s || "").toUpperCase().replace(/\s+/g, "").replace(/[-\\]/g, "/"); }
  function download(filename, text, mime) {
    var blob = new Blob([text], { type: mime || "text/csv;charset=utf-8" });
    var a = document.createElement("a");
    a.href = URL.createObjectURL(blob); a.download = filename;
    document.body.appendChild(a); a.click();
    setTimeout(function () { URL.revokeObjectURL(a.href); a.remove(); }, 500);
  }
  function toCSV(rows, cols) {
    function cell(v) { v = v == null ? "" : String(v); return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v; }
    var out = [cols.map(function (c) { return cell(c.label); }).join(",")];
    rows.forEach(function (r) { out.push(cols.map(function (c) { return cell(typeof c.get === "function" ? c.get(r) : r[c.key]); }).join(",")); });
    return "﻿" + out.join("\r\n"); // BOM so Excel reads UTF-8
  }
  // Print a report: fills #print-area and opens the browser print dialog ("Save as PDF")
  function printReport(title, innerHtml) {
    var area = $("#print-area");
    if (!area) { area = document.createElement("div"); area.id = "print-area"; document.body.appendChild(area); }
    area.innerHTML = "<div class='report'><div class='rhead'><b>" + esc(APP.name) + " (" + APP.short + ")</b><br>" +
      "Land &amp; Revenue Department, " + esc(APP.area) + "<br><h1>" + esc(title) + "</h1>" +
      "Generated: " + esc(fmtDateTime(new Date())) + (officer() ? " &nbsp;|&nbsp; By: " + esc(officer().id) : "") +
      "<br><b>DEMO PROTOTYPE - SAMPLE DATA ONLY. Not an official record.</b></div>" + innerHtml +
      "<p style='margin-top:14px;font-size:10px'>This report is generated by a decision-support system. It does not determine ownership, title or lawful possession. " +
      "Final decisions rest with the competent authority under applicable laws, rules and MCL procedures.</p></div>";
    setTimeout(function () { window.print(); }, 50);
  }

  // ---------- Reference lists ----------
  var STAGES = ["Submitted", "Under Scrutiny", "Field Verification Required", "Under Examination", "Action Taken", "Disposed"];
  var CATEGORIES = ["Land acquisition", "Compensation", "R&R", "Employment/CC/Annuity", "Plot identification/demarcation",
    "Physical possession", "Land records", "Mutation/document-related issue", "Rehabilitation issue", "Other"];
  var PLOT_STATUS = {
    Green: "Physical possession completed",
    Yellow: "Field verification pending",
    Orange: "Record/boundary discrepancy",
    Red: "Plot not identified / marking issue",
    Blue: "Field verification completed"
  };
  var STATUS_HEX = { Green: "#1a7f37", Yellow: "#c99700", Orange: "#d9641a", Red: "#c62828", Blue: "#1f6fd1" };
  function statusPill(code) {
    return "<span class='pill'><span class='dot " + esc(code) + "'></span>" + esc(code) + " - " + esc(PLOT_STATUS[code] || "") + "</span>";
  }
  function stagePill(stage) { return "<span class='pill'>" + esc(stage || "-") + "</span>"; }
  function stageToStatus(stage) { return stage === "Submitted" ? "Open" : stage === "Disposed" ? "Resolved" : "In progress"; }

  // ---------- DEMO officers and roles (NOT real authentication) ----------
  var ROLES = {
    SA:  { name: "Super Administrator", perms: ["grv.view", "grv.edit", "grv.assign", "grv.dispose", "plot.verify", "plot.status", "doc.ai", "reports", "audit", "users"] },
    LRO: { name: "Land & Revenue Officer", perms: ["grv.view", "grv.edit", "grv.assign", "plot.status", "doc.ai", "reports"] },
    FVO: { name: "Field Verification Officer", perms: ["grv.view", "plot.verify"] },
    GO:  { name: "Grievance Officer", perms: ["grv.view", "grv.edit", "grv.assign", "grv.dispose", "reports"] },
    RO:  { name: "Read-Only / Senior Officer", perms: ["grv.view", "reports", "audit"] }
  };
  var OFFICERS = [
    { id: "DEMO-SA-01",  role: "SA",  name: "Demo Administrator" },
    { id: "DEMO-LRO-01", role: "LRO", name: "Demo Land & Revenue Officer" },
    { id: "DEMO-GO-01",  role: "GO",  name: "Demo Grievance Officer" },
    { id: "DEMO-FVO-01", role: "FVO", name: "Demo Field Officer 1" },
    { id: "DEMO-FVO-02", role: "FVO", name: "Demo Field Officer 2" },
    { id: "DEMO-RO-01",  role: "RO",  name: "Demo Senior Officer (read-only)" }
  ];
  var SESSION_KEY = "lrms_demo_officer", TIMEOUT_MIN = 15;
  // Real login: officer accounts are Supabase users (email + password).
  // The database only lets logged-in users read grievances or change records.
  var authUser = null;
  var ready = !db ? Promise.resolve() : db.auth.getSession().then(function (r) {
    authUser = r && r.data && r.data.session ? r.data.session.user : null;
  }).catch(function () { authUser = null; });
  function clearRole() { try { sessionStorage.removeItem(SESSION_KEY); } catch (e) { /* ignore */ } }
  function officer() {
    if (!authUser) return null;
    try {
      var s = JSON.parse(sessionStorage.getItem(SESSION_KEY) || "null");
      if (!s || s.email !== authUser.email) return null;
      if (Date.now() - s.last > TIMEOUT_MIN * 60000) { clearRole(); if (db) db.auth.signOut(); authUser = null; return null; }
      return s;
    } catch (e) { return null; }
  }
  function touch() {
    try {
      var s = officer(); if (!s) return;
      s.last = Date.now(); sessionStorage.setItem(SESSION_KEY, JSON.stringify(s));
    } catch (e) { /* ignore */ }
  }
  function login(email, password) {
    if (!db) return Promise.resolve({ error: dbError });
    return db.auth.signInWithPassword({ email: email, password: password }).then(function (r) {
      if (!r.error && r.data) authUser = r.data.user;
      return r;
    });
  }
  // After login the officer picks a working role (role checks are still demo-level)
  function signIn(id) {
    var o = OFFICERS.filter(function (x) { return x.id === id; })[0];
    if (!o || !authUser) return null;
    var s = { id: o.id, name: o.name, role: o.role, roleName: ROLES[o.role].name, email: authUser.email, last: Date.now() };
    try { sessionStorage.setItem(SESSION_KEY, JSON.stringify(s)); } catch (e) { /* ignore */ }
    return s;
  }
  function signOut() {
    clearRole();
    (db ? db.auth.signOut() : Promise.resolve()).then(function () { location.reload(); }, function () { location.reload(); });
  }
  function can(perm) { var s = officer(); return !!(s && ROLES[s.role].perms.indexOf(perm) !== -1); }
  function histEntry(action, oldS, newS, extra) {
    var s = officer();
    var h = { at: new Date().toISOString(), by: s ? s.id : "Citizen", action: action, old_status: oldS || null, new_status: newS || null };
    if (extra) for (var k in extra) h[k] = extra[k];
    return h;
  }

  // ---------- Emblem: coal as the "black diamond" ----------
  function gem(cls) {
    var e = "stroke='#7fd6ff' stroke-width='1.6' stroke-linejoin='round'";
    return "<svg class='" + (cls || "") + "' viewBox='0 0 200 180' role='img' aria-label='Coal - the black diamond'>" +
      "<polygon points='30,50 65,15 75,50' fill='#2b3642' " + e + "/>" +
      "<polygon points='65,15 100,15 75,50' fill='#1b232c' " + e + "/>" +
      "<polygon points='100,15 75,50 125,50' fill='#323f4d' " + e + "/>" +
      "<polygon points='100,15 135,15 125,50' fill='#1b232c' " + e + "/>" +
      "<polygon points='135,15 170,50 125,50' fill='#141a21' " + e + "/>" +
      "<polygon points='30,50 75,50 100,165' fill='#0f141a' " + e + "/>" +
      "<polygon points='75,50 125,50 100,165' fill='#19212a' " + e + "/>" +
      "<polygon points='125,50 170,50 100,165' fill='#0a0e12' " + e + "/>" +
      "<path d='M150 4 L153 13 L162 16 L153 19 L150 28 L147 19 L138 16 L147 13 Z' fill='#e6f7ff'/>" +
      "</svg>";
  }

  // ---------- Header + menu (identical on every page) ----------
  var I18N = {
    en: {
      nav_home: "Home", nav_field: "Find Plot & Field", nav_dash: "Officer Dashboard",
      demo_banner: "DEMO PROTOTYPE - all plots, names and numbers are SAMPLE DATA. Do not enter real personal information.",
      tagline: "Land & Revenue - Kaniha Area (DEMO)"
    },
    hi: {
      nav_home: "मुख्य पृष्ठ", nav_field: "प्लॉट खोजें व क्षेत्र सत्यापन", nav_dash: "अधिकारी डैशबोर्ड",
      demo_banner: "डेमो प्रोटोटाइप - सभी प्लॉट, नाम और संख्याएँ नमूना डेटा हैं। कृपया वास्तविक व्यक्तिगत जानकारी न डालें।",
      tagline: "भूमि एवं राजस्व - कनिहा क्षेत्र (डेमो)"
    }
  };
  function lang() { try { return localStorage.getItem("lrms_lang") || "en"; } catch (e) { return "en"; } }
  function t(key) { var L = I18N[lang()] || I18N.en; return L[key] || I18N.en[key] || key; }
  function addStrings(dict) { for (var l in dict) { I18N[l] = I18N[l] || {}; for (var k in dict[l]) I18N[l][k] = dict[l][k]; } }
  function applyI18n() {
    $all("[data-i18n]").forEach(function (el) { el.textContent = t(el.getAttribute("data-i18n")); });
    document.documentElement.lang = lang() === "hi" ? "hi" : "en";
  }
  function renderHeader(active) {
    var head = document.createElement("div");
    head.innerHTML =
      "<header class='site-header'><div class='bar'>" +
      "<a class='brand' href='index.html'><div class='logo'>" + gem() + "</div><div><b>" + APP.short + "</b><span data-i18n='tagline'></span></div></a>" +
      "<nav class='site-nav' aria-label='Main menu'>" +
      "<a href='index.html' data-page='home' data-i18n='nav_home'></a>" +
      "<a href='field.html' data-page='field' data-i18n='nav_field'></a>" +
      "<a href='dashboard.html' data-page='dash' data-i18n='nav_dash'></a>" +
      "<button type='button' class='lang-btn' id='lang-btn' aria-label='Change language'>" + (lang() === "hi" ? "English" : "हिंदी") + "</button>" +
      "</nav></div></header>" +
      "<div class='demo-banner' data-i18n='demo_banner'></div>" +
      "<div class='officer-strip hidden' id='officer-strip'><div class='bar'></div></div>";
    while (head.firstChild) document.body.insertBefore(head.lastChild, document.body.firstChild);
    var a = $(".site-nav a[data-page='" + active + "']"); if (a) a.classList.add("active");
    $("#lang-btn").addEventListener("click", function () {
      try { localStorage.setItem("lrms_lang", lang() === "hi" ? "en" : "hi"); } catch (e) { /* ignore */ }
      location.reload();
    });
    ready.then(function () {
      var s = officer();
      if (!s) return;
      var strip = $("#officer-strip"); strip.classList.remove("hidden");
      $(".bar", strip).innerHTML = "<span>🔐 Signed in: <b>" + esc(s.id) + "</b> - " + esc(s.roleName) + " <span class='muted small'>(" + esc(s.email) + ")</span></span>" +
        "<span class='muted small'>Auto sign-out after " + TIMEOUT_MIN + " min of inactivity</span>" +
        "<button class='btn small secondary' id='signout-btn' style='margin-left:auto'>Sign out</button>";
      $("#signout-btn").addEventListener("click", signOut);
      ["click", "keydown", "touchstart"].forEach(function (ev) { document.addEventListener(ev, touch, { passive: true }); });
      setInterval(function () { if (!officer()) signOut(); }, 30000);
    });
    var f = document.createElement("footer"); f.className = "site-footer";
    f.innerHTML = "<p><b>" + esc(APP.name) + "</b> - an AI-assisted decision-support, GIS mapping, land-record management and grievance-tracking platform. " +
      "It does not declare ownership, decide title, determine lawful possession or alter official land records. Final decisions remain with competent authorities.</p>" +
      "<p>Prototype built for an IIM Sambalpur MDP by an MCL team. All data shown is fictional DEMO DATA.</p>";
    document.body.appendChild(f);
    applyI18n();
  }

  // ---------- Data loading ----------
  function loadRecords(type) {
    if (!db) return Promise.resolve({ data: [], error: dbError });
    var q = db.from(APP.table).select("*").order("created_at", { ascending: false }).limit(1000);
    if (type) q = q.eq("record_type", type);
    return q.then(function (r) { return { data: r.data || [], error: r.error }; });
  }

  // Apply saved plot updates (newest wins) on top of the DEMO baseline plots
  function mergePlotUpdates(plots, updates) {
    var byPlot = {};
    updates.slice().sort(function (a, b) { return new Date(a.created_at) - new Date(b.created_at); }).forEach(function (u) {
      (byPlot[u.plot_id] = byPlot[u.plot_id] || []).push(u);
    });
    return plots.map(function (p) {
      var c = JSON.parse(JSON.stringify(p));
      c.updates = byPlot[p.id] || [];
      c.updates.forEach(function (u) {
        var d = u.details || {};
        if (u.plot_status) c.status = u.plot_status;
        if (d.possession) c.possession = d.possession;
        if (d.demarcation) c.demarcation = d.demarcation;
        if (d.polygon && d.polygon.length >= 3) { c.polygon = d.polygon; c.polygonSource = "Field GPS survey"; c.confidence = null; }
        if (d.kind === "Field verification") { c.fieldStatus = "Completed"; c.lastVerification = u; }
        c.lastUpdatedBy = u.updated_by; c.lastUpdated = u.created_at;
      });
      return c;
    });
  }

  // ---------- AI helpers (run in the browser; results always need human review) ----------
  function levenshtein(a, b) {
    var m = a.length, n = b.length, d = [], i, j;
    for (i = 0; i <= m; i++) { d[i] = [i]; }
    for (j = 0; j <= n; j++) { d[0][j] = j; }
    for (i = 1; i <= m; i++) for (j = 1; j <= n; j++)
      d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    return d[m][n];
  }
  function similarity(a, b) {
    a = norm(a); b = norm(b); if (!a && !b) return 1;
    return 1 - levenshtein(a, b) / Math.max(a.length, b.length);
  }
  // Compare the sources held for one plot and flag possible discrepancies
  function detectDiscrepancies(p) {
    var out = [];
    if (p.areaAcq != null && p.areaRec != null && Math.abs(p.areaAcq - p.areaRec) >= 0.005) {
      out.push({ type: "Area", text: "Possible area discrepancy detected. Acquisition record: " + p.areaAcq.toFixed(2) +
        " acre; Land record: " + p.areaRec.toFixed(2) + " acre (difference " + Math.abs(p.areaAcq - p.areaRec).toFixed(2) + " acre)." });
    }
    (p.sources || []).forEach(function (s) {
      if (s.plot && normPlot(s.plot) !== normPlot(p.plot)) {
        out.push({ type: "Plot number", text: "Possible plot-number discrepancy detected. " + s.doc + " shows Plot No. " + s.plot + "; master record shows Plot No. " + p.plot + "." });
      }
      if (s.name && p.owner) {
        var sim = similarity(s.name, p.owner);
        if (sim < 1 && sim >= 0.6) out.push({ type: "Name", text: "Possible name variation detected (\"" + s.name + "\" in " + s.doc + " vs \"" + p.owner + "\", " + Math.round(sim * 100) + "% similar) - manual verification required. Similar names are NOT treated as the same legal person." });
        else if (sim < 0.6) out.push({ type: "Name", text: "Name differs between records (\"" + s.name + "\" in " + s.doc + " vs \"" + p.owner + "\") - manual verification required." });
      }
      if (s.khata && norm(s.khata) !== norm(p.khata)) {
        out.push({ type: "Khata", text: "Possible Khata discrepancy: " + s.doc + " shows Khata " + s.khata + "; master record shows " + p.khata + "." });
      }
    });
    return out;
  }
  // Simple keyword model for grievance categorisation and urgency (suggestion only)
  var CAT_WORDS = {
    "Compensation": ["compensation", "payment", "amount", "paid", "cheque", "money", "award amount", "मुआवजा"],
    "R&R": ["r&r", "resettlement", "rehabilitation colony", "house site", "displaced", "पुनर्वास"],
    "Employment/CC/Annuity": ["employment", "job", "annuity", "cc ", "cash compensation", "नौकरी"],
    "Plot identification/demarcation": ["demarcation", "boundary", "marking", "identify", "pillar", "measure", "सीमा"],
    "Physical possession": ["possession", "occupied", "encroach", "cultivating", "कब्जा"],
    "Land records": ["record", "khata", "rot", "patta", "khatian", "अभिलेख"],
    "Mutation/document-related issue": ["mutation", "certificate", "document", "deed"],
    "Land acquisition": ["acquisition", "acquired", "notification", "section"],
    "Rehabilitation issue": ["rehabilitation", "colony", "drinking water", "school", "road"]
  };
  function suggestCategory(text) {
    var tx = " " + String(text || "").toLowerCase() + " ", best = null, bestN = 0;
    for (var c in CAT_WORDS) {
      var n = CAT_WORDS[c].filter(function (w) { return tx.indexOf(w) !== -1; }).length;
      if (n > bestN) { best = c; bestN = n; }
    }
    var urgent = /(threat|violence|crop|harvest|construction|demolish|blocked|urgent|immediately|elderly|medical|flood|danger)/i.test(tx);
    return { category: best, urgency: urgent ? "High" : best ? "Medium" : "Low", matches: bestN };
  }

  // ---------- Geometry (for measurement and GPS polygons) ----------
  function areaSqm(latlngs) {
    if (!latlngs || latlngs.length < 3) return 0;
    var R = 6378137, lat0 = latlngs[0][0] * Math.PI / 180, pts = latlngs.map(function (p) {
      return [p[1] * Math.PI / 180 * R * Math.cos(lat0), p[0] * Math.PI / 180 * R];
    }), s = 0;
    for (var i = 0; i < pts.length; i++) { var a = pts[i], b = pts[(i + 1) % pts.length]; s += a[0] * b[1] - b[0] * a[1]; }
    return Math.abs(s / 2);
  }
  function sqmToAcre(m) { return m / 4046.8564224; }
  function distM(a, b) {
    var R = 6371000, dLat = (b[0] - a[0]) * Math.PI / 180, dLng = (b[1] - a[1]) * Math.PI / 180;
    var x = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.cos(a[0] * Math.PI / 180) * Math.cos(b[0] * Math.PI / 180) * Math.sin(dLng / 2) * Math.sin(dLng / 2);
    return 2 * R * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x));
  }
  function centroid(poly) {
    var la = 0, ln = 0; poly.forEach(function (p) { la += p[0]; ln += p[1]; });
    return [la / poly.length, ln / poly.length];
  }

  return {
    APP: APP, db: db, dbError: dbError, $: $, $all: $all, esc: esc, fmtDate: fmtDate, fmtDateTime: fmtDateTime,
    errText: errText, showMsg: showMsg, dbReady: dbReady, norm: norm, normPlot: normPlot, download: download, toCSV: toCSV,
    printReport: printReport, STAGES: STAGES, CATEGORIES: CATEGORIES, PLOT_STATUS: PLOT_STATUS, STATUS_HEX: STATUS_HEX,
    statusPill: statusPill, stagePill: stagePill, stageToStatus: stageToStatus, ROLES: ROLES, OFFICERS: OFFICERS,
    gem: gem, officer: officer, signIn: signIn, signOut: signOut, login: login, ready: ready,
    authUser: function () { return authUser; }, can: can, histEntry: histEntry, t: t, lang: lang,
    addStrings: addStrings, applyI18n: applyI18n, renderHeader: renderHeader, loadRecords: loadRecords,
    mergePlotUpdates: mergePlotUpdates, similarity: similarity, detectDiscrepancies: detectDiscrepancies,
    suggestCategory: suggestCategory, areaSqm: areaSqm, sqmToAcre: sqmToAcre, distM: distM, centroid: centroid
  };
})();
